/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Obj.Kardex;
import Obj.Cliente;
import Obj.Empleado;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Dildo__Queen
 */
public class Clientes extends javax.swing.JPanel {

    private Kardex krdx = null;
    private Empleado empld = null;
    private Cliente clintTmp;

    /**
     *
     * @param kardex
     * @param emplado
     */
    public Clientes(Kardex kardex, Empleado emplado) {
        this.krdx = kardex;
        this.empld = emplado;
        initComponents();
        init();
    }

    public void init() {
        this.btnEliminar.setEnabled(this.empld.isAdministrator());
        this.btnEditar.setEnabled(this.empld.isAdministrator());
        this.tblTodos.setModel(new AbstractTableModel() {
            String[] nmColumnas = {"Identificacion", "Nombre", "Telefono", "Direccion"};

            @Override
            public String getColumnName(int column) {
                return nmColumnas[column];
            }

            @Override
            public int getRowCount() {
                try {
                    if (!krdx.getClientes().isEmpty()) {
                        return krdx.getClientes().size();
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
                }
                return 0;
            }

            @Override
            public int getColumnCount() {
                return nmColumnas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                try {
                    Cliente ctmp = (Cliente) krdx.getClientes().get(rowIndex);
                    if (columnIndex == 0) {
                        return ctmp.getIdentificacion();
                    } else if (columnIndex == 1) {
                        return ctmp.getNombre();
                    } else if (columnIndex == 2) {
                        return ctmp.getTelefono();
                    } else if (columnIndex == 3) {
                        return ctmp.getDireccion();
                    }
                } catch (Exception e) {
                    Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, e);
                }
                return "";
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProductoNuevo = new javax.swing.JPanel();
        lblClienteId = new javax.swing.JLabel();
        lblClienteNombre = new javax.swing.JLabel();
        lblClienteTelefono = new javax.swing.JLabel();
        lblClienteDireccion = new javax.swing.JLabel();
        txtfLClienteId = new javax.swing.JTextField();
        txtfClienteNombre = new javax.swing.JTextField();
        txtfClienteTelefono = new javax.swing.JTextField();
        txtfClienteDireccion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        pnlClientes = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        scpTodosLosProductos = new javax.swing.JScrollPane();
        tblTodos = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(472, 600));

        pnlProductoNuevo.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo cliente"));

        lblClienteId.setText("Identificacion:");

        lblClienteNombre.setText("Nombre:");

        lblClienteTelefono.setText("Telefono:");

        lblClienteDireccion.setText("Direccion:");

        txtfClienteDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtAddProducto(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtAddProducto(evt);
            }
        });

        javax.swing.GroupLayout pnlProductoNuevoLayout = new javax.swing.GroupLayout(pnlProductoNuevo);
        pnlProductoNuevo.setLayout(pnlProductoNuevoLayout);
        pnlProductoNuevoLayout.setHorizontalGroup(
            pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                        .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClienteNombre))
                        .addGap(18, 18, 18)
                        .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                                .addComponent(lblClienteTelefono)
                                .addGap(0, 176, Short.MAX_VALUE))
                            .addComponent(txtfClienteTelefono)))
                    .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                        .addComponent(lblClienteId)
                        .addGap(18, 18, 18)
                        .addComponent(txtfLClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar))
                    .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                        .addComponent(lblClienteDireccion)
                        .addGap(18, 18, 18)
                        .addComponent(txtfClienteDireccion)))
                .addContainerGap())
        );
        pnlProductoNuevoLayout.setVerticalGroup(
            pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteId)
                    .addComponent(txtfLClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteNombre)
                    .addComponent(lblClienteTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteDireccion)
                    .addComponent(txtfClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Todos los productos"));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtEditar(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtEliminar(evt);
            }
        });

        tblTodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpTodosLosProductos.setViewportView(tblTodos);

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpTodosLosProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addContainerGap())
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(scpTodosLosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProductoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProductoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EvtAddProducto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtAddProducto
        try {
            if (clintTmp != null) {
                clintTmp.setNombre(txtfClienteNombre.getText().trim());
                clintTmp.setTelefono(txtfClienteTelefono.getText().trim());
                clintTmp.setDireccion(txtfClienteDireccion.getText().trim());
                this.krdx.edit(clintTmp);
                this.clintTmp = null;
                txtfLClienteId.setText("");
                txtfClienteNombre.setText("");
                txtfClienteTelefono.setText("");
                txtfClienteDireccion.setText("");
            } else {
                krdx.add(new Cliente(txtfLClienteId.getText().toUpperCase(), txtfClienteNombre.getText().trim(), txtfClienteTelefono.getText().trim(), txtfClienteDireccion.getText().trim()));
                txtfLClienteId.setText("");
                txtfClienteNombre.setText("");
                txtfClienteTelefono.setText("");
                txtfClienteDireccion.setText("");
            }
            tblTodos.updateUI();
        } catch (Exception ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "La operacion no se pudo completar\n\n" + ex.getMessage(), krdx.getNombre() + " Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EvtAddProducto

    private void EvtEditar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtEditar
        try {
            this.clintTmp = (Cliente) this.krdx.getClientes().get(this.tblTodos.getSelectedRow());
            this.txtfLClienteId.setText(this.clintTmp.getIdentificacion());
            this.txtfClienteNombre.setText(this.clintTmp.getNombre());
            this.txtfClienteTelefono.setText(this.clintTmp.getTelefono());
            this.txtfClienteDireccion.setText(this.clintTmp.getDireccion());
        } catch (Exception ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "La operacion no se pudo completar\n\n" + ex.getMessage(), krdx.getNombre() + " Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EvtEditar

    private void EvtEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtEliminar
        try {
            int a;
            this.clintTmp = (Cliente) this.krdx.getClientes().get(this.tblTodos.getSelectedRow());
            a = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar el cliente: \n" + clintTmp.toString(), "Eliminar producto", JOptionPane.WARNING_MESSAGE);
            if (a == 0) {
                this.krdx.remove(clintTmp);
                tblTodos.updateUI();
                this.clintTmp = null;
            }else{
                JOptionPane.showMessageDialog(null, "Operacion cancelada", "Eliminar cliente", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EvtEliminar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblClienteDireccion;
    private javax.swing.JLabel lblClienteId;
    private javax.swing.JLabel lblClienteNombre;
    private javax.swing.JLabel lblClienteTelefono;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlProductoNuevo;
    private javax.swing.JScrollPane scpTodosLosProductos;
    private javax.swing.JTable tblTodos;
    private javax.swing.JTextField txtfClienteDireccion;
    private javax.swing.JTextField txtfClienteNombre;
    private javax.swing.JTextField txtfClienteTelefono;
    private javax.swing.JTextField txtfLClienteId;
    // End of variables declaration//GEN-END:variables
}
