/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Obj.Empleado;
import Obj.Kardex;
import Obj.Producto;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Dildo__Queen
 */
public class Productos extends javax.swing.JPanel {

    private Kardex krdx = null;
    private Empleado empld = null;
    private Producto prodctTmp = null;

    /**
     *
     * @param kardex
     * @param empleado
     */
    public Productos(Kardex kardex, Empleado empleado) {
        this.krdx = kardex;
        this.empld = empleado;
        initComponents();
        init();
    }

    public void init() {
        this.btnEliminar.setEnabled(this.empld.isAdministrator());
        this.btnEditar.setEnabled(this.empld.isAdministrator());
        this.tblTodos.setModel(new AbstractTableModel() {
            String[] nmColumnas = {"Codigo", "Nombre", "Costo", "Descripcion"};

            @Override
            public String getColumnName(int column) {
                return nmColumnas[column];
            }

            @Override
            public int getRowCount() {
                try {
                    if (!krdx.getProductos().isEmpty()) {
                        return krdx.getProductos().size();
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
                return 0;
            }

            @Override
            public int getColumnCount() {
                return nmColumnas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                try {
                    Producto ptmp = (Producto) krdx.getProductos().get(rowIndex);
                    if (columnIndex == 0) {
                        return ptmp.getCodigo();
                    } else if (columnIndex == 1) {
                        return ptmp.getNombre();
                    } else if (columnIndex == 2) {
                        return ptmp.getCosto();
                    } else if (columnIndex == 3) {
                        return ptmp.getDescripcion();
                    }
                } catch (Exception e) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, e);
                }
                return "";
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProductoNuevo = new javax.swing.JPanel();
        lblNuevoCodigo = new javax.swing.JLabel();
        lblNuevoNombre = new javax.swing.JLabel();
        lblNuevoDescripcion = new javax.swing.JLabel();
        lblNuevoCosto = new javax.swing.JLabel();
        txtfNuevoCodigo = new javax.swing.JTextField();
        txtfNuevoNombre = new javax.swing.JTextField();
        txtfNuevoDescripcion = new javax.swing.JTextField();
        txtfNuevoCosto = new javax.swing.JTextField();
        btnNuevoProducto = new javax.swing.JButton();
        pnlProductos = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        scpTodosLosProductos = new javax.swing.JScrollPane();
        tblTodos = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(472, 600));

        pnlProductoNuevo.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo producto"));

        lblNuevoCodigo.setText("Codigo:");

        lblNuevoNombre.setText("Nombre:");

        lblNuevoDescripcion.setText("Descripcion:");

        lblNuevoCosto.setText("Costo:");

        txtfNuevoCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtAddProducto(evt);
            }
        });

        btnNuevoProducto.setText("Guardar");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtAddProducto(evt);
            }
        });

        javax.swing.GroupLayout pnlProductoNuevoLayout = new javax.swing.GroupLayout(pnlProductoNuevo);
        pnlProductoNuevo.setLayout(pnlProductoNuevoLayout);
        pnlProductoNuevoLayout.setHorizontalGroup(
            pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                        .addComponent(lblNuevoCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtfNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNuevoNombre)
                        .addGap(18, 18, 18)
                        .addComponent(txtfNuevoNombre))
                    .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                        .addComponent(lblNuevoDescripcion)
                        .addGap(18, 18, 18)
                        .addComponent(txtfNuevoDescripcion))
                    .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                        .addComponent(lblNuevoCosto)
                        .addGap(18, 18, 18)
                        .addComponent(txtfNuevoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevoProducto)
                        .addGap(0, 141, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlProductoNuevoLayout.setVerticalGroup(
            pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoCodigo)
                    .addComponent(txtfNuevoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevoNombre)
                    .addComponent(txtfNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoDescripcion)
                    .addComponent(txtfNuevoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoCosto)
                    .addComponent(btnNuevoProducto)
                    .addComponent(txtfNuevoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Todos los productos"));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtEditar(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtEliminar(evt);
            }
        });

        tblTodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpTodosLosProductos.setViewportView(tblTodos);

        javax.swing.GroupLayout pnlProductosLayout = new javax.swing.GroupLayout(pnlProductos);
        pnlProductos.setLayout(pnlProductosLayout);
        pnlProductosLayout.setHorizontalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpTodosLosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addContainerGap())
        );
        pnlProductosLayout.setVerticalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(scpTodosLosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProductoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProductoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EvtAddProducto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtAddProducto
        try {
            if (prodctTmp != null) {
                prodctTmp.setNombre(txtfNuevoNombre.getText().trim());
                prodctTmp.setDescripcion(txtfNuevoDescripcion.getText().trim());
                prodctTmp.setCosto(Double.parseDouble(txtfNuevoCosto.getText().trim()));
                this.krdx.edit(prodctTmp);
                this.prodctTmp = null;
                txtfNuevoCodigo.setText("");
                txtfNuevoNombre.setText("");
                txtfNuevoDescripcion.setText("");
                txtfNuevoCosto.setText("");
            } else {
                krdx.add(new Producto(txtfNuevoCodigo.getText().toUpperCase(), txtfNuevoNombre.getText().trim(), txtfNuevoDescripcion.getText().trim(), Double.parseDouble(txtfNuevoCosto.getText().trim())));
                txtfNuevoCodigo.setText("");
                txtfNuevoNombre.setText("");
                txtfNuevoDescripcion.setText("");
                txtfNuevoCosto.setText("");
            }
            tblTodos.updateUI();
        } catch (Exception ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "La operacion no se pudo completar\n\n" + ex.getMessage(), krdx.getNombre() + " Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EvtAddProducto

    private void EvtEditar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtEditar
        try {
            this.prodctTmp = (Producto) this.krdx.getProductos().get(this.tblTodos.getSelectedRow());
            this.txtfNuevoCodigo.setText(this.prodctTmp.getCodigo());
            this.txtfNuevoNombre.setText(this.prodctTmp.getNombre());
            this.txtfNuevoDescripcion.setText(this.prodctTmp.getDescripcion());
            this.txtfNuevoCosto.setText(this.prodctTmp.getCosto() + "");
        } catch (Exception ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "La operacion no se pudo completar\n\n" + ex.getMessage(), krdx.getNombre() + " Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EvtEditar

    private void EvtEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtEliminar
        try {
            int a;
            this.prodctTmp = (Producto) this.krdx.getProductos().get(this.tblTodos.getSelectedRow());
            a = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar el producto: \n" + prodctTmp.toString(), "Eliminar producto", JOptionPane.WARNING_MESSAGE);
            if (a == 0) {
                this.krdx.remove(prodctTmp);
                tblTodos.updateUI();
                this.prodctTmp = null;
            } else {
                JOptionPane.showMessageDialog(null, "Operacion cancelada", "Eliminar producto", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "La operacion no se pudo completar\n\n" + ex.getMessage(), krdx.getNombre() + " Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EvtEliminar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JLabel lblNuevoCodigo;
    private javax.swing.JLabel lblNuevoCosto;
    private javax.swing.JLabel lblNuevoDescripcion;
    private javax.swing.JLabel lblNuevoNombre;
    private javax.swing.JPanel pnlProductoNuevo;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JScrollPane scpTodosLosProductos;
    private javax.swing.JTable tblTodos;
    private javax.swing.JTextField txtfNuevoCodigo;
    private javax.swing.JTextField txtfNuevoCosto;
    private javax.swing.JTextField txtfNuevoDescripcion;
    private javax.swing.JTextField txtfNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
