/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Gui.FramesAux.RealizarAbonoVentanueva;
import Obj.Cliente;
import Obj.Empleado;
import Obj.Item;
import Obj.Kardex;
import Obj.Producto;
import Obj.Venta;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Dildo__Queen
 */
public class RealizarVenta extends javax.swing.JPanel {

    private Kardex krdx = null;
    private Empleado empld = null;
    private Cliente clnt = null;
    private Venta ventTemp = null;
    private Producto prodctTemp = null;
    public MainFrame appRun = null;

    /**
     *
     * @param kardex
     * @param vendedor
     * @param app
     */
    public RealizarVenta(Kardex kardex, Empleado vendedor, MainFrame app) {
        this.krdx = kardex;
        this.empld = vendedor;
        this.appRun = app;
        this.ventTemp = new Venta(this.empld, clnt);
        initComponents();
        init();
    }

    public void init() {
        txtfIdVenta.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        txtfVendedorId.setText(this.empld.getIdentificacion());
        txtfVendedorNombre.setText(this.empld.getNombre());
        tblVentas.setModel(new AbstractTableModel() {
            String[] nmColumnas = {"Codigo", "Nombre", "Cantidad", "Valor unitario", "Subtotal"};

            @Override
            public String getColumnName(int column) {
                return nmColumnas[column];
            }

            @Override
            public int getRowCount() {
                if (ventTemp.getItems().isEmpty()) {
                    return 0;
                }
                return ventTemp.getItems().size();
            }

            @Override
            public int getColumnCount() {
                return nmColumnas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Item itmp = ventTemp.getItems().get(rowIndex);
                if (columnIndex == 0) {
                    return itmp.getProducto().getCodigo();
                } else if (columnIndex == 1) {
                    return itmp.getProducto().getNombre();
                } else if (columnIndex == 2) {
                    return itmp.getCantidad();
                } else if (columnIndex == 3) {
                    return itmp.getProducto().getCosto();
                } else if (columnIndex == 4) {
                    return itmp.getSubtotal();
                }
                return "";
            }
        }
        );
    }

    public void newVenta() {
        ventTemp = new Venta(this.empld, clnt);
        tblVentas.updateUI();
        clnt = null;
        txtfClienteId.setText("");
        txtfClienteNombre.setText("");
        txtfProductoId.setText("");
        txtfProductoDescripcion.setText("");
        txtfTotal.setText("");
        txtfSaldo.setText("");
        txtfClienteId.setEnabled(true);
        txtfClienteNombre.setEnabled(true);
        btnBuscar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFecha = new javax.swing.JLabel();
        lblfVendedorId = new javax.swing.JLabel();
        lblVendedorNombre = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtfIdVenta = new javax.swing.JTextField();
        pnlCliente = new javax.swing.JPanel();
        lblClienteNombre = new javax.swing.JLabel();
        txtfClienteNombre = new javax.swing.JTextField();
        lblClienteId = new javax.swing.JLabel();
        txtfClienteId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAnonimo = new javax.swing.JButton();
        txtfVendedorId = new javax.swing.JTextField();
        txtfVendedorNombre = new javax.swing.JTextField();
        txtfProductoId = new javax.swing.JTextField();
        txtfProductoDescripcion = new javax.swing.JTextField();
        spnCantidad = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        scpVentas = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();
        btnAbono = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtfTotal = new javax.swing.JFormattedTextField();
        txtfSaldo = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(472, 603));

        lblFecha.setText("Fecha:");

        lblfVendedorId.setText("Identificacion:");

        lblVendedorNombre.setText("Nombre:");

        lblCantidad.setText("Cantidad:");

        lblProducto.setText("Producto:");

        lblTotal.setText("Total:");

        lblSaldo.setText("Saldo:");

        txtfIdVenta.setFocusable(false);

        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        lblClienteNombre.setText("Nombre:");

        txtfClienteNombre.setFocusable(false);

        lblClienteId.setText("Identificacion:");

        txtfClienteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtBuscarCliente(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtBuscarCliente(evt);
            }
        });

        btnAnonimo.setText("Anonimo");
        btnAnonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtAnonimo(evt);
            }
        });

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(lblClienteId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblClienteNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfClienteNombre))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnonimo)))
                .addContainerGap())
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteId)
                    .addComponent(txtfClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClienteNombre)
                    .addComponent(txtfClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnonimo)
                    .addComponent(btnBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtfVendedorId.setFocusable(false);

        txtfVendedorNombre.setFocusable(false);

        txtfProductoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtFindProducto(evt);
            }
        });

        txtfProductoDescripcion.setFocusable(false);

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtAddToCar(evt);
            }
        });

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpVentas.setViewportView(tblVentas);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtRemoveToCar(evt);
            }
        });

        btnAbono.setText("Nuevo abono");
        btnAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtNuevoAbono(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtAddVenta(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtCancelarVenta(evt);
            }
        });

        txtfTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤########################,##0.##"))));
        txtfTotal.setFocusable(false);

        txtfSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤########################,##0.##"))));
        txtfSaldo.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpVentas)
                    .addComponent(pnlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addGap(18, 18, 18)
                                .addComponent(txtfIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblfVendedorId)
                                .addGap(18, 18, 18)
                                .addComponent(txtfVendedorId)))
                        .addGap(18, 18, 18)
                        .addComponent(lblVendedorNombre)
                        .addGap(18, 18, 18)
                        .addComponent(txtfVendedorNombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProducto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfProductoId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfProductoDescripcion)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spnCantidad)
                            .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemover, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAceptar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAbono))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSaldo)
                                .addGap(18, 18, 18)
                                .addComponent(txtfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtfIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfVendedorId)
                    .addComponent(txtfVendedorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVendedorNombre)
                    .addComponent(txtfVendedorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(lblCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txtfProductoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfProductoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scpVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRemover)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbono))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EvtAnonimo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtAnonimo
        txtfClienteId.setText("No id");
        txtfClienteNombre.setText("Anonimo");
        txtfClienteId.setEnabled(false);
        txtfClienteNombre.setEnabled(false);
        btnBuscar.setEnabled(false);
        clnt = null;
        this.ventTemp.setCliente(clnt);
    }//GEN-LAST:event_EvtAnonimo

    private void EvtBuscarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtBuscarCliente
        if (!txtfClienteId.getText().equals("".trim())) {
            try {
                clnt = (Cliente) this.krdx.findCliente(txtfClienteId.getText());
                txtfClienteNombre.setText(clnt.getNombre());
                this.ventTemp.setCliente(clnt);
            } catch (Exception ex) {
                Logger.getLogger(RealizarVenta.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Warning\n\n" + ex.getMessage(), this.krdx.getNombre() + " Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_EvtBuscarCliente

    private void EvtAddToCar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtAddToCar
        try {
            ventTemp.add(new Item(new Integer(spnCantidad.getValue() + ""), krdx.findProducto(txtfProductoId.getText())));
            spnCantidad.setValue(new Integer("1"));
        } catch (Exception ex) {
            Logger.getLogger(RealizarVenta.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Warning\n\n" + ex.getMessage(), this.krdx.getNombre() + " Warning", JOptionPane.WARNING_MESSAGE);
        }
        txtfTotal.setValue(ventTemp.getSubtotal());
        txtfSaldo.setValue(ventTemp.getSaldoPorPagar());
        tblVentas.updateUI();
    }//GEN-LAST:event_EvtAddToCar

    private void EvtRemoveToCar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtRemoveToCar
        try {
            Item itmp = (Item) ventTemp.getItems().get(tblVentas.getSelectedRow());
            ventTemp.remove(itmp);
        } catch (Exception ex) {
            Logger.getLogger(RealizarVenta.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(pnlCliente, "La operacion no se puede realizar\n\n" + ex.getMessage(), krdx.getNombre() + "Warning", JOptionPane.WARNING_MESSAGE);
        }
        tblVentas.updateUI();
        txtfTotal.setValue(ventTemp.getSubtotal());
        txtfSaldo.setValue(ventTemp.getSaldoPorPagar());
    }//GEN-LAST:event_EvtRemoveToCar

    private void EvtAddVenta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtAddVenta
        try {
            if (!ventTemp.getItems().isEmpty()) {
                this.krdx.add(ventTemp);
                newVenta();
            }
        } catch (Exception ex) {
            Logger.getLogger(RealizarVenta.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Warning\n\n" + ex.getMessage(), this.krdx.getNombre() + " Warning", JOptionPane.WARNING_MESSAGE);
        }
        this.appRun.vents.tblTodas.updateUI();
    }//GEN-LAST:event_EvtAddVenta

    private void EvtCancelarVenta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtCancelarVenta
        newVenta();
        this.appRun.vents.tblTodas.updateUI();
    }//GEN-LAST:event_EvtCancelarVenta

    private void EvtFindProducto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtFindProducto
        try {
            prodctTemp = (Producto) this.krdx.findProducto(txtfProductoId.getText());
            this.txtfProductoDescripcion.setText(prodctTemp.getNombre());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(pnlCliente, "Busqueda de producto\n" + ex.getMessage(), "Busqueda de producto", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(RealizarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EvtFindProducto

    private void EvtNuevoAbono(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtNuevoAbono
        new RealizarAbonoVentanueva(appRun, ventTemp, empld).setVisible(true);
    }//GEN-LAST:event_EvtNuevoAbono

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbono;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAnonimo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblClienteId;
    private javax.swing.JLabel lblClienteNombre;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVendedorNombre;
    private javax.swing.JLabel lblfVendedorId;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JScrollPane scpVentas;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtfClienteId;
    private javax.swing.JTextField txtfClienteNombre;
    private javax.swing.JTextField txtfIdVenta;
    private javax.swing.JTextField txtfProductoDescripcion;
    private javax.swing.JTextField txtfProductoId;
    public javax.swing.JFormattedTextField txtfSaldo;
    private javax.swing.JFormattedTextField txtfTotal;
    private javax.swing.JTextField txtfVendedorId;
    private javax.swing.JTextField txtfVendedorNombre;
    // End of variables declaration//GEN-END:variables
}
